### ISSUE TITLE
tzapu Wifimanger 1.0.0

### ISSUE THREAD

**Issue by Moko0815** [helmarw/myClock#2]
where can i found this?
highest version is 0.15, but is not working:

```
W:\Arduino\myClock\arduino-1.8.10\portable\sketchbook\myClock\WiFi.ino: In function 'void startWiFi()':

WiFi:41:30: error: no matching function for call to 'WiFiManager::WiFiManager(Stream&)'

   WiFiManager wifiManager(OUT);

                              ^

W:\Arduino\myClock\arduino-1.8.10\portable\sketchbook\myClock\WiFi.ino:41:30: note: candidate is:

In file included from W:\Arduino\myClock\arduino-1.8.10\portable\sketchbook\myClock\myClock.ino:13:0:

W:\Arduino\myClock\arduino-1.8.10\portable\sketchbook\libraries\WiFiManager/WiFiManager.h:74:5: note: WiFiManager::WiFiManager()

     WiFiManager();

     ^

W:\Arduino\myClock\arduino-1.8.10\portable\sketchbook\libraries\WiFiManager/WiFiManager.h:74:5: note:   candidate expects 0 arguments, 1 provided

WiFi:45:15: error: 'class WiFiManager' has no member named 'setClass'

   wifiManager.setClass("invert");               // dark theme

```

**Comment by helmarw** [comment]
might help to actually read comments in ino :)
#include <WiFiManager.h>        // works with version 1.0.0 https://github.com/tzapu/WiFiManager/tree/development

**Comment by Moko0815** [comment]
sorry, but not everyone  has englisch as native language
i can't find a link to 1.0.0 on the page, but v2.0.3 (installed via library manager) works too :)

**Comment by helmarw** [comment]
me neither, still its not difficult to understand that 0.15 wont work if i write it works with 1.0 from development
thats why i write comment sin any of may code, as much as possible, at least i try ...
doesnt mean it cant work with newer versions, but i did not test them yet
good to know it works
